language: php

php:
  - 5.6
  - 7.0
  - 7.1

branches:
  except:
    - 3.3.2
    - v5
    - laravel-fix
    - laravel-fix-54

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit